### ISSUE TITLE
Error in differential abundance analysis

### ISSUE THREAD

**Issue by PrincessTiabeanie** [cafferychen777/ggpicrust2#1]
Hi,
I tried to use your package for my dataset and only got it to work partly. The requirements for the input format for the functions are quite rigid, and then also not the same for all the functions. It would be nice if you could harmonise this.
Until then, for everyone with the same problem, here's the code that worked for me:

```
library(ggpicrust2)
#I used the picrust2_pipeline.py script, so those are the path and name automatically given to the file.
abundance_file <- "picrust2_out_pipeline/KO_metagenome_out/pred_metagenome_unstrat.tsv"
abundance <- ko2kegg_abundance(abundance_file)

#using metadata from a phyloseq object, so first converting to a normal dataframe
meta <- data.frame(sample_data(physeq))
meta$sample_name <- rownames(meta) #important to name the column sample_name
meta <- tibble(meta)

#I'm comparing different water bodies
group <- "water_body"

#this is the only command that needs the abundance table as a matrix and metadata as a dataframe.
#Additionally, the sample names need to be in a column which is called "sample_names", although this is nowhere stated in the documentation. 
pathway_heatmap(as.matrix(abundance), data.frame(meta), group)+
               theme(axis.text.x = element_text(size = 8, color = "black")) #to add sample names

pathway_pca(abundance = abundance, metadata = meta, group = group)

daa <- pathway_daa(abundance = abundance, metadata = meta, group = group,
                   daa_method = "ALDEx2")
daa_kegg <- pathway_annotation(daa_results_df = daa, ko_to_kegg = TRUE)

```
This is how far I got. 
pathway_errorbar() needs the package ggprism to be installed, maybe this should be added as a dependency?
But it still doesn't work, here's the code I tried:
```
pathway_errorbar(abundance = abundance,
                 daa_results_df = daa_kegg[1:20,],  #subsetting to have less than 30
                 Group = meta$water_body,
                 ko_to_kegg = TRUE,
                 p_values_threshold = 0.05,
                 order = "group",
                 select = NULL,
                 p_value_bar = TRUE,
                 colors = NULL,
                 x_lab = NULL)
```

The error message is: _Insufficient values in manual scale. 3 needed but only 2 provided._
Doesn't work either when I provide colors manually by setting colors = c("blue", "green", "red"). Any idea how to fix this?
In addition, I couldn't figure out how to use the select parameter, tried select = c("ko05340", "ko00562") but that didn't work, so I resorted to subsetting the input dataframe.

Other remarks:
It would be cool if you could select to plot PC3 and PC4 in the PCA, not only PC1 and PC2.
How to add the group labels in the heatmap as you did in the paper preprint?

Thanks for creating this package!

**Comment by cafferychen777** [comment]
Thank you for using ggpicrust2! I guess I know what’going on. I will address the problem shortly. I believe I can give you a good answer tomorrow. Thank you again

**Comment by cafferychen777** [comment]
Thank you for using ggpicrust2! I guess I know what’going on. I will address the problem shortly. I believe I can give you a good answer tomorrow. Thank you again.

**Comment by cafferychen777** [comment]
Thank you for taking the time to provide feedback on the ggpicrust2 package. I appreciate your detailed message, and I'm glad to hear that you've managed to make progress with your dataset. I will address your concerns and provide suggestions below.

First, I apologize for any inconvenience the input format requirements may have caused. I understand that having consistent input formats across all functions would be helpful, and I will work on harmonizing this in future updates.

Regarding the pathway_errorbar() issue, I apologize for the oversight in my code. I have fixed the bug and submitted a new version to CRAN that addresses this issue. In the meantime, the function should work as expected when nlevels(Group) = 2. I will notify you as soon as the updated version is available for download.

As for the select parameter, I have been able to use it without any issues, and I couldn't find any problems in the code after checking it again. I will continue to double-check and monitor its functionality.

Regarding the group labels for the pathway_heatmap, this is indeed a feature in the upcoming version. However, as it is not yet fully stable, I would like to wait until it is more reliable before releasing it. In the meantime, you can use software like Adobe Illustrator to manually add the labels to the heatmap.

As for your other remarks, I will consider adding the option to plot PC3 and PC4 in the PCA function in a future update. Thank you for the suggestion.

Lastly, I will make sure to include ggprism as a dependency in the package's documentation to prevent further confusion.

Thank you once again for your valuable feedback. Please feel free to reach out if you have any further questions or concerns.

**Comment by cafferychen777** [comment]
> Hi, I tried to use your package for my dataset and only got it to work partly. The requirements for the input format for the functions are quite rigid, and then also not the same for all the functions. It would be nice if you could harmonise this. Until then, for everyone with the same problem, here's the code that worked for me:
> 
> ```
> library(ggpicrust2)
> #I used the picrust2_pipeline.py script, so those are the path and name automatically given to the file.
> abundance_file <- "picrust2_out_pipeline/KO_metagenome_out/pred_metagenome_unstrat.tsv"
> abundance <- ko2kegg_abundance(abundance_file)
> 
> #using metadata from a phyloseq object, so first converting to a normal dataframe
> meta <- data.frame(sample_data(physeq))
> meta$sample_name <- rownames(meta) #important to name the column sample_name
> meta <- tibble(meta)
> 
> #I'm comparing different water bodies
> group <- "water_body"
> 
> #this is the only command that needs the abundance table as a matrix and metadata as a dataframe.
> #Additionally, the sample names need to be in a column which is called "sample_names", although this is nowhere stated in the documentation. 
> pathway_heatmap(as.matrix(abundance), data.frame(meta), group)+
>                theme(axis.text.x = element_text(size = 8, color = "black")) #to add sample names
> 
> pathway_pca(abundance = abundance, metadata = meta, group = group)
> 
> daa <- pathway_daa(abundance = abundance, metadata = meta, group = group,
>                    daa_method = "ALDEx2")
> daa_kegg <- pathway_annotation(daa_results_df = daa, ko_to_kegg = TRUE)
> ```
> 
> This is how far I got. pathway_errorbar() needs the package ggprism to be installed, maybe this should be added as a dependency? But it still doesn't work, here's the code I tried:
> 
> ```
> pathway_errorbar(abundance = abundance,
>                  daa_results_df = daa_kegg[1:20,],  #subsetting to have less than 30
>                  Group = meta$water_body,
>                  ko_to_kegg = TRUE,
>                  p_values_threshold = 0.05,
>                  order = "group",
>                  select = NULL,
>                  p_value_bar = TRUE,
>                  colors = NULL,
>                  x_lab = NULL)
> ```
> 
> The error message is: _Insufficient values in manual scale. 3 needed but only 2 provided._ Doesn't work either when I provide colors manually by setting colors = c("blue", "green", "red"). Any idea how to fix this? In addition, I couldn't figure out how to use the select parameter, tried select = c("ko05340", "ko00562") but that didn't work, so I resorted to subsetting the input dataframe.
> 
> Other remarks: It would be cool if you could select to plot PC3 and PC4 in the PCA, not only PC1 and PC2. How to add the group labels in the heatmap as you did in the paper preprint?
> 
> Thanks for creating this package!

I think you can use the renewed version to check its work.
```
# install.packages("devtools")
devtools::install_github("cafferychen777/ggpicrust2")
```

**Comment by cafferychen777** [comment]
> 

Dear Sonja,

Glad to hear that the ggprism package is working well for you now. As for the issue you encountered with the PCA plot, you mentioned that you received an error message stating "cannot rescale a constant/zero column to unit variance." This error can occur when some of the traits only appear in the samples you removed, and are therefore zero in the ones you want to plot.

In light of the potential concerns with automatically removing zero rows, it may be worthwhile to consider alternative approaches for addressing this issue. For example, one could filter out low-abundance features instead of true zeros, which may be a more statistically justified method. However, I appreciate your suggestion to add an option to automatically remove zero rows in the pathway_pca function. While this may not be feasible to implement in the current version of the package, I will certainly consider this for future updates.

Regarding the title mismatch, no worries about that. It's great that you were able to fix your initial issue. If you have any further questions or concerns, feel free to reach out.

Thank you for bringing up this issue, and please let me know if you have any further thoughts or questions. I will be happy to respond as soon as possible.

Best,
Chen YANG

**Comment by cafferychen777** [comment]
I forgot explaining it. In your message, you suggested modifying the pathway_pca function to automatically remove zero rows when using subsets of data. While this would be a nice-to-have feature, it is important to consider that in microbiome data, the "zeros" in the counts may not always represent true absence, as they can be influenced by factors such as library size and PCR amplification efficiency. Therefore, automatic removal of zero rows may not always be statistically justified, and it may be worthwhile to consider other methods for addressing this issue, such as filtering out low-abundance features instead of true zeros.

**Comment by PrincessTiabeanie** [comment]
Hey, I'm sorry, but I don't understand your point. Don't you do the same? The command ko2kegg_abundance() outputs the message _"The kegg pathway with zero abundance in all the different samples has been removed."_ So this also removes zero rows.

I stumbled across another detail that was confusing me. The legend in the heatmap says "Abundance (%)", same in the pathway_errorbar() plot. Is that correct? I can't see in your code where you convert relative abundance in decimals to percent. 
Additionally, I'd love to hear your explanation why you use the relative abundance across samples (not within each sample), this is not intuitive to me. Does the data have to be rarefied/normalized before that? Otherwise, if I have a sample that has 10 times as many reads as the others, everything would show up as red, wouldn't it? Other people use e.g. [Z-scores](https://davetang.org/muse/2018/05/15/making-a-heatmap-in-r-with-the-pheatmap-package/) for plotting heatmaps.
I'm used to ASV abundance data and just started working with functional predictions about a week ago, so I'm still trying to understand the differences between analyzing gene abundance vs ASV abundance.

Thanks again for your amazing support here! Great work!

**Comment by cafferychen777** [comment]
Ok, I will address your questions shortly. I can explain it.

**Comment by cafferychen777** [comment]
Dear Sonja,

Thank you for your reply and additional input. To address your concerns and suggestions, please find the following clarifications:

- Regarding the removal of pathways with zero abundance in all samples in ko2kegg_abundance():

This is indeed a controversial topic in statistics, and different researchers have varying opinions on data preprocessing. When writing the ko2kegg_abundance() code, it was a dilemma whether to remove the pathways with zero abundance in all samples. However, due to practical considerations, such as the risk of overwhelming the KEGG database with excessive requests during pathway annotation, this removal step was included.

- Concerning the "Abundance (%)" label in the heatmap and pathway_errorbar() plot:

The choice to label the heatmap with "Abundance (%)" instead of "Relative Abundance" was primarily made for aesthetic reasons, as the latter is quite long. We understand that this might be slightly misleading, and users can adjust the labels in the code if they prefer.

- About using relative abundance across samples in the heatmap:

The heatmap is a descriptive visualization rather than a strict statistical test. To facilitate better visualization of the differences in pathways, the relative abundance across samples (not within each sample) was chosen. You correctly pointed out that rarefying/normalizing the data before plotting the heatmap could be beneficial. Other approaches like using Z-scores for plotting heatmaps are also valid. We appreciate your suggestion, and we'll work on improving the pathway_heatmap() function in future iterations.

Once again, thank you for your valuable feedback. If you have any further questions or concerns, please don't hesitate to reach out.

Best regards,

Chen YANG

**Comment by cafferychen777** [comment]
Dear Sonja,

I have made some modifications to the pathway_heatmap function, and it is now possible to use Z-score for normalization.

Please feel free to use the updated version of pathway_heatmap in your analysis. If you have any questions or concerns, please do not hesitate to reach out to me.

Best regards,
Chen YANG
