### ISSUE TITLE
Error encountered in the command pathway_annotation()

### ISSUE THREAD

**Issue by ivanllampy** [cafferychen777/ggpicrust2#16]
Dear Caffery,

Thank you for developing the ggpicrust2 package! 
I followed the codes on the tutorial with my own dataset, I ran the command pathway_annotation():
`daa_annotated_sub_method_results_df <-
  pathway_annotation(pathway = "KO",
                     daa_results_df = daa_sub_method_results_df[1:50,],
                     ko_to_kegg = TRUE)`
but encountered the following error:
`Error in curl::curl_fetch_memory(url, handle = handle) :    Failure when receiving data from the peer`
May I have some advice on how to solve it, thank you!

Best regards,
Ivan

**Comment by cafferychen777** [comment]
Dear Ivan,

Thank you for your message and I'm glad to hear that you are using the ggpicrust2 package.

Regarding the error message you encountered, "Failure when receiving data from the peer", this error is usually related to network connectivity issues. It could be caused by a temporary network interruption, firewall restrictions, or other network-related issues.

Here are some troubleshooting steps that you can try:

- Check your internet connection and make sure you are connected to the internet.
- Check if there are any firewall restrictions that could be blocking the package from accessing the necessary resources.
- Try running the pathway_annotation() function again after a few minutes, as it could be a temporary network issue that resolves on its own.

I hope this helps! Let me know if you have any further questions or concerns.

Best regards,
Chen YANG

**Comment by ivanllampy** [comment]
Dear Caffery,

Thank you for your quick reply!
I re-ran the code on another computer, it works fine.
Seems it is the problem of my computer/internet as you mentioned. I will try troubleshoot with your suggestions.
Thank you!

Best regards,
Ivan
