### ISSUE TITLE
"FuncDiv" for functional diversity visualization using ggpicrust2?

### ISSUE THREAD

**Issue by marwa38** [cafferychen777/ggpicrust2#30]
Many thanks for this tool. 
Is any tutorial help to use ggpicrust2 for alpha and beta contributional diversity (or functional diversity) visualization? https://github.com/gavinmdouglas/FuncDiv
alpha and beta contributional diversity are new terms introduced by one of the developers of picrust2
Thanks again

**Comment by cafferychen777** [comment]
Dear @marwa38 ,

Thank you for reaching out and expressing your appreciation for the tool. I'm glad to hear that you find it useful.

Regarding your question about a tutorial for using ggpicrust2 for alpha and beta contributional diversity visualization, currently, such a tutorial is not available. However, I believe it's a great idea and I will definitely consider adding this functionality in the future.

I appreciate your suggestion, and please feel free to reach out if you have any further questions or feedback.

Best regards,
Chen

**Comment by cafferychen777** [comment]
Dear @marwa38 ,

I hope you're doing well. Thank you for following up on the enhancement regarding the ggpicrust2 tutorial for alpha and beta contributional diversity visualization.

I sincerely apologize for the delay. Due to my commitments with applying to graduate school and the development of MicrobiomeStat, my schedule has been exceptionally tight. I understand the importance of this enhancement, and I genuinely want to address it. However, it seems I will only be able to allocate dedicated time for this after April of next year.

I deeply appreciate your patience and understanding on this matter. Please know that your feedback is highly valued, and I'm committed to improving the tool based on user feedback like yours.

Wishing you all the best and thank you once again for your continued support.

Warm regards,
Chen

**Comment by marwa38** [comment]
Dear Caffery @cafferychen777 
Any updates on this enhancement option please ? Thanks for understanding.

**Comment by marwa38** [comment]
@cafferychen777 
@olivroy 
Hi team 
This is a kind reminder of my last year request.
Cheers
Marwa

**Comment by cafferychen777** [comment]
Dear Marwa,

I apologize for the delayed response. Over the past six months, I've been focused on applying to PhD programs. Additionally, as I'm planning to shift my research focus towards statistical methods, I likely won't be adding this functionality to ggpicrust2.

Moving forward, ggpicrust2 will be maintained with its current feature set. I appreciate your interest and patience regarding this enhancement.

Thank you for your understanding.

Best regards,
Caffery

**Comment by marwa38** [comment]
thanks for letting me know, Caffery
