### ISSUE TITLE
Error in curl::curl_fetch_memory

### ISSUE THREAD

**Issue by luozhy88** [cafferychen777/ggpicrust2#4]
感谢作者发布这么好用的工具，有个bug，还请帮助查看：
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/94740863/229268935-f946487f-6265-4c21-bc44-1f4b5cb4abeb.png">

**Comment by luozhy88** [comment]
SSL peer certificate or SSH remote key was not OK: [rest.kegg.jp] SSL certificate problem: certificate has expired

**Comment by cafferychen777** [comment]
这个应该是网络的问题，你有挂全局代理吗？
This should be a network problem, do you have a global proxy hooked up?

**Comment by cafferychen777** [comment]
This error could be caused by an expired SSL certificate on the KEGG website. Here are a few possible solutions:

Update the certificate: You can try updating the root certificate on your computer. This can be done by downloading and installing the latest root certificate in your operating system's certificate store. The process may vary depending on your operating system. You can search online for "how to update root certificate (with your operating system)" to find relevant instructions.

Disable SSL verification: While not recommended, you can try disabling SSL verification when connecting to the KEGG website. In R, you can disable SSL verification when connecting to the KEGG website using the following code:
```
library(httr)
set_config(config(ssl_verifypeer = 0L))
```
This will disable SSL verification when connecting to the KEGG website, but doing so may make your connection less secure.

I hope these solutions help you resolve the issue.

**Comment by cafferychen777** [comment]
Hello @luozhy88 ,

Thank you for your using!
If you are in China, make sure your computer network can break through the firewall.

Best regards

**Comment by cafferychen777** [comment]
Hello @luozhy88  ,

Thank you for using ggpicrust2 and bringing your issue to our attention. We apologize for the inconvenience you experienced.

May I ask if the solution I provided earlier helped resolve your issue?

**Comment by luozhy88** [comment]
Thanks! other bug!
<img width="996" alt="image" src="https://user-images.githubusercontent.com/94740863/229280698-3f63c361-afb9-4199-9d89-4cf0f5440aab.png">

**Comment by cafferychen777** [comment]
It has been updated in version 1.4.11 .
Please update the version

```
# Install ggpicrust2 from GitHub
devtools::install_github("cafferychen777/ggpicrust2")
```

Or set select = "NULL"

Best regards

**Comment by luozhy88** [comment]
我已经更新 1.4.12版本，但我的mac 使用clashx 没有全局模式，只有规则模式，如何处理：

<img width="945" alt="image" src="https://user-images.githubusercontent.com/94740863/229289910-473c44e6-32d9-4610-968d-ca42fb75bf70.png">

**Comment by cafferychen777** [comment]
<img width="487" alt="截屏2023-04-01 20 53 53" src="https://user-images.githubusercontent.com/82987086/229290054-029df96a-2e21-43d7-9901-3fbf8a38ac7a.png">

Hello @luozhy88 

To clarify, ClashX does have a global mode, so if you're not seeing it in your settings, it could be due to a configuration issue or a bug. If you have updated to version 1.4.12 and are experiencing issues with ClashX not showing the global mode, but only the rule mode, there are a few things you can try.

First, make sure that you have enabled the global mode in the ClashX settings. You can do this by going to the preferences window and selecting the "General" tab. Then, check the "Use global mode" option and save your changes.

If you're still not able to see the global mode, you may want to check if there's a newer version of ClashX available, or try checking your ClashX configuration file to ensure that it is correctly pointing to the Clash binary that corresponds to the updated version. You can find the configuration file by clicking on the "Open config folder" button in the preferences window. Once you have located the file, open it in a text editor and look for the "binary-path" option. Make sure that it points to the correct path of the updated Clash binary.

If you're still having issues, you may want to try restarting ClashX and/or your Mac to see if that resolves the problem. If none of these steps work, you may need to seek further technical assistance from the developers or the ClashX community.

Best Regards,

**Comment by luozhy88** [comment]
感谢您的回复，可能我mac电脑配置问题，clashx模式中全局，我曾启用过，但是全局模式整个网络都是无网状态。
 curl::curl_fetch_memory(url, handle = handle) 这个curl中url是指什么，我可以改下我的host，以便于我可以直接访问它

**Comment by cafferychen777** [comment]
I think that's not the point. Maybe you should change your vpn software to shadow rocket or shadow rocket x.

**Comment by luozhy88** [comment]
VPN 代理是其中选择之一，也有其他方式可以连接，我想知道这个url 是什么

**Comment by cafferychen777** [comment]
I think you can find it in [KEGGREST function document](https://github.com/Bioconductor/KEGGREST/blob/devel/R/KEGGREST.R).

**Comment by luozhy88** [comment]
it works in KEGG ! I set global model on my mac

**Comment by cckeneally** [comment]
If anyone else is having this issue, but you are able to connect to kegg.rest.jp in your browser (so it's not a network issue). Try updating KEGGREST and R version to latest - fixed the issue for me.
