### ISSUE TITLE
pathway_errorbar(): In the results of the pathway_errorbar plot, the p-values cannot be fully displayed

### ISSUE THREAD

**Issue by benzodiazepines** [cafferychen777/ggpicrust2#57]
In the results of the pathway_errorbar plot, the p-values on the right side cannot be fully displayed. The p-values are represented in scientific notation, and only the first part of the number plus 'e' is shown in the generated image. The specific exponent of 'e' is not completely displayed."

**Comment by cafferychen777** [comment]
Hello @benzodiazepines ,

Thank you for bringing this issue to our attention. The problem you're facing with the incomplete display of p-values in the `pathway_errorbar` plot is due to the scientific notation not being fully displayed in the image.

You can resolve this issue by rounding the p-values to a specific number of decimal places, which will allow them to be fully displayed in the plot. You can use the following code snippet to accomplish this:

```R
daa_results_df$p_adjust <- round(daa_results_df$p_adjust, 5)
```

This will round the p-values in the `daa_results_df$p_adjust` column to 5 decimal places. After running this line, you can proceed to generate the `pathway_errorbar` plot again, and you should find that the p-values are now completely displayed.

Please let me know if this resolves the issue, or if you have any further questions.

Best regards,
Chen YANG
